apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-service
  template:
    metadata:
      labels:
        app: mlops-service
    spec:
      containers:
      - name: mlops-service
        image: mlops-service:latest
        imagePullPolicy: Never # <- wichtig, sonst sucht er nach dem Image online
        ports:
        - containerPort: 8080
